http:
  port: 8080
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 10s


student_postgres:
  host: 172.16.23.26
  port: 7432
  username: postgres
  dbname: postgres
  password: student

secrets:
  access_secret: is9G63gdsHa73V62WfJ84
  password_salt: sj37dGtaH37dgF5D4a2bl

domains:
  image: http://172.16.23.26:8080/